workflow: standard
created: 2026-07-16T04:14:34.317Z
status: active
current_artifact: intent
base_versions: {}
artifacts:
  intent: ready
  stories: pending
  spec: pending
  research: pending
  design: pending
  tasks: pending
  implementation: pending
  verification: pending
artifact_timings:
  intent:
    started: 2026-07-16T04:14:41.937Z
artifact_tokens:
  intent:
    context: 775
    budget: 20000
