workflow: standard
created: 2026-04-15T03:59:57.673Z
status: active
current_artifact: stories
base_versions: {}
artifacts:
  intent: complete
  spec: complete
  research: complete
  design: complete
  tasks: complete
  implementation: complete
  verification: ready
  stories: complete
