import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtemp, mkdir, rm, writeFile, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DocGenerator, type DocGenerateResult } from '../src/docs/doc-generator.js'
import { DocsConfigSchema } from '../src/schemas/project-config.js'

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

let projectRoot: string
let specDir: string

async function seedArchiveEntry(dirName: string, summary: string): Promise<void> {
  const dir = join(specDir, 'archive', dirName)
  await mkdir(dir, { recursive: true })
  await writeFile(join(dir, 'summary.md'), summary, 'utf-8')
}

async function writeReleasesYaml(content: string): Promise<void> {
  await writeFile(join(specDir, 'releases.yaml'), content, 'utf-8')
}

async function generateChangelog(): Promise<{ result: DocGenerateResult; content: string }> {
  const config = DocsConfigSchema.parse({ types: ['changelog'] })
  const generator = new DocGenerator(specDir, projectRoot, config)
  const result = await generator.generate(['changelog'])
  const content = await readFile(join(projectRoot, 'docs', 'changelog.md'), 'utf-8')
  return { result, content }
}

const VALID_RECORD_YAML = [
  'releases:',
  '  - version: 0.5.0',
  '    tag: v0.5.0',
  '    date: 2026-05-02',
  '    changes:',
  '      - 2026-05-01-alpha',
  '  - version: 0.4.0',
  '    tag: v0.4.0',
  '    date: 2026-04-02',
  '    changes:',
  '      - 2026-04-01-beta',
  '',
].join('\n')

beforeEach(async () => {
  projectRoot = await mkdtemp(join(tmpdir(), 'metta-doc-gen-versioned-'))
  specDir = join(projectRoot, 'spec')
  await mkdir(join(specDir, 'archive'), { recursive: true })
  await seedArchiveEntry('2026-05-01-alpha', 'Alpha summary.\n')
  await seedArchiveEntry('2026-04-01-beta', 'Beta summary.\n')
})

afterEach(async () => {
  await rm(projectRoot, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 })
})

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('DocGenerator versioned changelog', () => {
  it('record absent: output is byte-identical to the flat format', async () => {
    const { result, content } = await generateChangelog()

    const expected =
      '<!-- Generated by Metta — do not edit directly -->\n' +
      '<!-- Sources: spec/archive/2026-05-01-alpha/summary.md, spec/archive/2026-04-01-beta/summary.md -->\n' +
      '<!-- Run `metta docs generate` to regenerate -->\n' +
      '# Changelog\n' +
      '\n' +
      '## 2026-05-01 — alpha\n' +
      '\n' +
      'Alpha summary.\n' +
      '\n' +
      '\n' +
      '## 2026-04-01 — beta\n' +
      '\n' +
      'Beta summary.\n' +
      '\n'

    expect(content).toBe(expected)
    expect(result.warnings).toEqual([])
  })

  it('record present: renders version sections newest-first with H3 entry blocks', async () => {
    await writeReleasesYaml(VALID_RECORD_YAML)

    const { result, content } = await generateChangelog()

    expect(content).toContain('## 0.5.0 — 2026-05-02\n')
    expect(content).toContain('## 0.4.0 — 2026-04-02\n')
    expect(content.indexOf('## 0.5.0 — 2026-05-02')).toBeLessThan(
      content.indexOf('## 0.4.0 — 2026-04-02'),
    )

    // Entries render as H3 blocks inside their version group.
    expect(content).toContain('### 2026-05-01 — alpha\n\nAlpha summary.\n')
    expect(content).toContain('### 2026-04-01 — beta\n\nBeta summary.\n')
    // No flat H2 date-entry headings remain.
    expect(content).not.toMatch(/^## 2026-05-01 — alpha/m)
    expect(content).not.toMatch(/^## 2026-04-01 — beta/m)
    // All entries attributed — no Unreleased section.
    expect(content).not.toContain('## Unreleased')
    // Each entry appears exactly once.
    expect(content.match(/2026-05-01 — alpha/g)).toHaveLength(1)
    expect(content.match(/2026-04-01 — beta/g)).toHaveLength(1)

    expect(result.warnings).toEqual([])
  })

  it('renders an Unreleased section for a newly archived change not in the record', async () => {
    await writeReleasesYaml(VALID_RECORD_YAML)
    await seedArchiveEntry('2026-06-01-gamma', 'Gamma summary.\n')

    const { content } = await generateChangelog()

    expect(content).toContain('## Unreleased\n')
    expect(content).toContain('### 2026-06-01 — gamma\n\nGamma summary.\n')

    // Unreleased comes before all version sections.
    expect(content.indexOf('## Unreleased')).toBeLessThan(content.indexOf('## 0.5.0'))
    // gamma appears only under Unreleased.
    expect(content.match(/2026-06-01 — gamma/g)).toHaveLength(1)
  })

  it('corrupt releases.yaml: warns and falls back to flat format without throwing', async () => {
    await writeReleasesYaml('releases: "not an array"\n')

    const { result, content } = await generateChangelog()

    expect(result.warnings).toContain(
      'spec/releases.yaml is invalid — falling back to flat changelog format',
    )
    // Flat rendering: H2 date-entry headings, no version/Unreleased sections.
    expect(content).toContain('## 2026-05-01 — alpha\n')
    expect(content).toContain('## 2026-04-01 — beta\n')
    expect(content).not.toContain('## Unreleased')
    expect(content).not.toContain('0.5.0')
    expect(content).not.toContain('###')
  })

  it('malformed YAML syntax also degrades to the flat format with a warning', async () => {
    await writeReleasesYaml('releases: [unclosed\n')

    const { result, content } = await generateChangelog()

    expect(result.warnings).toContain(
      'spec/releases.yaml is invalid — falling back to flat changelog format',
    )
    expect(content).toContain('## 2026-05-01 — alpha\n')
  })

  it('finalize regeneration: versioned shape survives with the new change under Unreleased', async () => {
    await writeReleasesYaml(VALID_RECORD_YAML)

    // First generation: fully attributed, versioned shape, no Unreleased.
    const first = await generateChangelog()
    expect(first.content).toContain('## 0.5.0 — 2026-05-02')
    expect(first.content).not.toContain('## Unreleased')

    // Finalize archives a new change, then regenerates docs with a fresh
    // DocGenerator over the same specDir (call sites unchanged).
    await seedArchiveEntry('2026-07-01-delta', 'Delta summary.\n')
    const second = await generateChangelog()

    // New change lands under Unreleased; does not revert to flat format.
    expect(second.content).toContain('## Unreleased\n')
    expect(second.content).toContain('### 2026-07-01 — delta\n\nDelta summary.\n')
    // Version sections remain intact with their entries.
    expect(second.content).toContain('## 0.5.0 — 2026-05-02\n')
    expect(second.content).toContain('### 2026-05-01 — alpha\n\nAlpha summary.\n')
    expect(second.content).toContain('## 0.4.0 — 2026-04-02\n')
    expect(second.content).toContain('### 2026-04-01 — beta\n\nBeta summary.\n')
    // No entry appears twice.
    expect(second.content.match(/2026-07-01 — delta/g)).toHaveLength(1)
    expect(second.content.match(/2026-05-01 — alpha/g)).toHaveLength(1)
  })
})
