workflow: standard
created: 2026-04-17T05:01:44.831Z
status: abandoned
current_artifact: stories
base_versions: {}
artifacts:
  intent: complete
  stories: ready
  spec: pending
  research: pending
  design: pending
  tasks: pending
  implementation: pending
  verification: pending
